'use client';

import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { businessCalendarApi } from '@/lib/api';

type Activity = { id: string; title: string; description?: string; startDate: string; endDate: string; startTime?: string; endTime?: string; status: string; priority: string; category?: { name: string; color?: string }; venue?: string; notes?: string };

const date = (value?: string) => value ? new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(value)) : 'TBC';
const dateRange = (item: Activity) => date(item.startDate) === date(item.endDate) ? date(item.startDate) : `${date(item.startDate)} - ${date(item.endDate)}`;

export default function BusinessCalendarPage() {
  const queryClient = useQueryClient();
  const [selected, setSelected] = useState<string>('');
  const [view, setView] = useState<'table' | 'timeline'>('table');
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState({ title: '', startDate: '', endDate: '', startTime: '', categoryId: '', venue: '', notes: '' });
  const calendars = useQuery({ queryKey: ['business-calendar'], queryFn: () => businessCalendarApi.list().then((r) => r.data) });
  const calendarId = selected || calendars.data?.[0]?.id || '';
  const activities = useQuery<Activity[]>({ queryKey: ['business-calendar', calendarId, 'activities'], queryFn: () => businessCalendarApi.activities(calendarId).then((r) => r.data), enabled: Boolean(calendarId) });
  const categories = useQuery({ queryKey: ['business-calendar', 'categories'], queryFn: () => businessCalendarApi.categories().then((r) => r.data) });
  const create = useMutation({ mutationFn: () => businessCalendarApi.createActivity(calendarId, { ...form, endDate: form.endDate || form.startDate, allDay: !form.startTime, status: 'PLANNED', priority: 'NORMAL' }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['business-calendar', calendarId, 'activities'] }); setOpen(false); setForm({ title: '', startDate: '', endDate: '', startTime: '', categoryId: '', venue: '', notes: '' }); } });
  const current = calendars.data?.find((item: any) => item.id === calendarId);
  const rows = activities.data || [];
  const meetings = rows.filter((row) => row.category?.name?.toLowerCase().includes('meeting')).length;
  const deadlines = rows.filter((row) => row.deadline).length;
  const completed = rows.filter((row) => row.status === 'COMPLETED').length;

  return <main className="min-h-screen bg-[#f4f7f9] px-4 py-6 text-slate-900 sm:px-8">
    <div className="mx-auto max-w-[1500px] space-y-6">
      <header className="rounded-2xl bg-[#123047] px-6 py-7 text-white shadow-xl sm:px-9">
        <div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-cyan-200">Institutional activity management</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">School Business Calendar Hub</h1><p className="mt-2 max-w-2xl text-sm text-slate-200">One authoritative calendar for meetings, CPD, monitoring, assessments, deadlines and school events.</p></div><div className="flex flex-wrap gap-3"><a className="rounded-lg border border-white/30 px-4 py-2 text-sm font-semibold hover:bg-white/10" href={calendarId ? businessCalendarApi.templateUrl(calendarId) : '#'}>Download template</a><button className="rounded-lg bg-cyan-300 px-4 py-2 text-sm font-bold text-[#123047] hover:bg-cyan-200" onClick={() => setOpen(true)} disabled={!calendarId}>Add activity</button></div></div>
      </header>
      <section className="grid grid-cols-2 gap-3 md:grid-cols-4"><Metric label="Total activities" value={rows.length} accent="text-cyan-700" /><Metric label="Meetings" value={meetings} accent="text-indigo-700" /><Metric label="Deadlines" value={deadlines} accent="text-amber-700" /><Metric label="Completed" value={completed} accent="text-emerald-700" /></section>
      <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-4 border-b border-slate-200 p-5 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-slate-500">Official term calendar</p><h2 className="mt-1 text-xl font-bold">{current?.name || 'Select a calendar'}</h2><p className="text-sm text-slate-500">{current?.academicYear?.name || ''} {current?.term?.name ? `· ${current.term.name}` : ''} · <span className="font-semibold text-emerald-700">{current?.status || 'Loading'}</span></p></div><div className="flex flex-wrap gap-2"><select className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-medium" value={calendarId} onChange={(e) => setSelected(e.target.value)}><option value="">Choose calendar</option>{(calendars.data || []).map((item: any) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><div className="flex rounded-lg border border-slate-300 p-1 text-sm"><button className={`rounded px-3 py-1.5 ${view === 'table' ? 'bg-[#123047] text-white' : ''}`} onClick={() => setView('table')}>Table</button><button className={`rounded px-3 py-1.5 ${view === 'timeline' ? 'bg-[#123047] text-white' : ''}`} onClick={() => setView('timeline')}>Timeline</button></div></div></div>
        {view === 'table' ? <div className="overflow-x-auto"><table className="min-w-[900px] w-full text-left text-sm"><thead className="bg-slate-100 text-xs font-bold uppercase tracking-wide text-slate-700"><tr><th className="px-5 py-4">#</th><th className="px-3 py-4">Activity</th><th className="px-3 py-4">Category</th><th className="px-3 py-4">Date / time</th><th className="px-3 py-4">Venue</th><th className="px-3 py-4">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row, index) => <tr key={row.id} className="hover:bg-cyan-50/40"><td className="px-5 py-4 font-bold text-slate-400">{String(index + 1).padStart(2, '0')}</td><td className="px-3 py-4"><p className="font-bold text-slate-900">{row.title}</p><p className="mt-1 max-w-sm text-xs text-slate-500">{row.description || row.notes || 'No additional notes'}</p></td><td className="px-3 py-4"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold text-slate-700">{row.category?.name || 'Uncategorised'}</span></td><td className="px-3 py-4 font-medium text-slate-700"><p>{dateRange(row)}</p><p className="text-xs text-slate-500">{row.startTime || 'All day'}{row.endTime ? ` - ${row.endTime}` : ''}</p></td><td className="px-3 py-4 text-slate-600">{row.venue || 'TBC'}</td><td className="px-3 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${row.status === 'COMPLETED' ? 'bg-emerald-100 text-emerald-800' : row.status === 'CANCELLED' ? 'bg-rose-100 text-rose-800' : 'bg-blue-100 text-blue-800'}`}>{row.status}</span></td></tr>)}</tbody></table>{!rows.length && <div className="p-12 text-center text-sm text-slate-500">No activities yet. Use the official Excel template or add the first activity.</div>}</div> : <div className="space-y-3 p-5">{rows.map((row) => <div key={row.id} className="border-l-4 border-cyan-500 bg-slate-50 p-4"><div className="flex flex-wrap justify-between gap-2"><strong>{row.title}</strong><span className="text-sm font-semibold text-slate-600">{dateRange(row)}</span></div><p className="mt-1 text-sm text-slate-500">{row.startTime || 'All day'} · {row.category?.name || 'Uncategorised'} · {row.venue || 'Venue TBC'}</p></div>)}</div>}</section>
    </div>
    {open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><form className="w-full max-w-xl rounded-2xl bg-white p-6 shadow-2xl" onSubmit={(e) => { e.preventDefault(); create.mutate(); }}><div className="flex items-start justify-between"><div><h2 className="text-xl font-bold">Add calendar activity</h2><p className="mt-1 text-sm text-slate-500">This writes directly to the authoritative CalendarActivity record.</p></div><button type="button" onClick={() => setOpen(false)} className="text-2xl text-slate-400">×</button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><span className="label">Activity name</span><input required className="field" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label><span className="label">Start date</span><input required type="date" className="field" value={form.startDate} onChange={(e) => setForm({ ...form, startDate: e.target.value })} /></label><label><span className="label">End date</span><input type="date" className="field" value={form.endDate} onChange={(e) => setForm({ ...form, endDate: e.target.value })} /></label><label><span className="label">Start time</span><input type="time" className="field" value={form.startTime} onChange={(e) => setForm({ ...form, startTime: e.target.value })} /></label><label><span className="label">Category</span><select required className="field" value={form.categoryId} onChange={(e) => setForm({ ...form, categoryId: e.target.value })}><option value="">Choose category</option>{(categories.data || []).map((item: any) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="sm:col-span-2"><span className="label">Venue</span><input className="field" value={form.venue} onChange={(e) => setForm({ ...form, venue: e.target.value })} /></label><label className="sm:col-span-2"><span className="label">Notes</span><textarea className="field min-h-20" value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></label></div><button disabled={create.isPending} className="mt-5 w-full rounded-lg bg-[#123047] px-4 py-3 font-bold text-white">{create.isPending ? 'Saving...' : 'Save activity'}</button></form></div>}
    <style jsx>{`.label{display:block;margin-bottom:.35rem;font-size:.75rem;font-weight:700;color:#475569}.field{width:100%;border:1px solid #cbd5e1;border-radius:.5rem;padding:.65rem .75rem;font-size:.875rem;outline:none}.field:focus{border-color:#0891b2;box-shadow:0 0 0 2px #cffafe}`}</style>
  </main>;
}

function Metric({ label, value, accent }: { label: string; value: number; accent: string }) { return <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</p><p className={`mt-2 text-3xl font-black ${accent}`}>{value}</p></div>; }
