export const REPORT_COMPONENT_TYPES = {
  TEXT_BLOCK: { label: 'Text Block', icon: 'Type', category: 'Text' },
  HEADING: { label: 'Heading', icon: 'Heading', category: 'Text' },
  PARAGRAPH: { label: 'Paragraph', icon: 'FileText', category: 'Text' },
  DIVIDER: { label: 'Divider', icon: 'Minus', category: 'Layout' },
  SPACER: { label: 'Spacer', icon: 'Expand', category: 'Layout' },
  IMAGE: { label: 'Image', icon: 'Image', category: 'Media' },
  SCHOOL_LOGO: { label: 'School Logo', icon: 'Building2', category: 'School' },
  SCHOOL_NAME: { label: 'School Name', icon: 'Building2', category: 'School' },
  SCHOOL_INFO: { label: 'School Info', icon: 'Info', category: 'School' },
  STUDENT_NAME: { label: 'Student Name', icon: 'User', category: 'Student' },
  STUDENT_PHOTO: { label: 'Student Photo', icon: 'Camera', category: 'Student' },
  STUDENT_INFO: { label: 'Student Info', icon: 'UserCircle', category: 'Student' },
  STUDENT_PROFILE_CARD: { label: 'Profile Card', icon: 'IdCard', category: 'Student' },
  CLASS_NAME: { label: 'Class Name', icon: 'Users', category: 'Academic' },
  TERM_INFO: { label: 'Term Info', icon: 'Calendar', category: 'Academic' },
  RESULTS_TABLE: { label: 'Results Table', icon: 'Table', category: 'Data' },
  SUBJECT_TABLE: { label: 'Subject Table', icon: 'BookOpen', category: 'Data' },
  GRADE_TABLE: { label: 'Grade Table', icon: 'Award', category: 'Data' },
  ATTENDANCE_TABLE: { label: 'Attendance Table', icon: 'ClipboardCheck', category: 'Data' },
  RANKING_TABLE: { label: 'Ranking Table', icon: 'Trophy', category: 'Analytics' },
  PERFORMANCE_CHART: { label: 'Bar Chart', icon: 'BarChart3', category: 'Analytics' },
  RADAR_CHART: { label: 'Radar Chart', icon: 'Radar', category: 'Analytics' },
  LINE_CHART: { label: 'Line Chart', icon: 'TrendingUp', category: 'Analytics' },
  HEATMAP: { label: 'Heatmap', icon: 'Grid3x3', category: 'Analytics' },
  COMPETENCY_HEATMAP: { label: 'Competency Map', icon: 'Brain', category: 'Analytics' },
  ANALYTICS_SUMMARY: { label: 'Stats Summary', icon: 'BarChart4', category: 'Analytics' },
  TEACHER_REMARKS: { label: 'Teacher Remarks', icon: 'MessageSquare', category: 'Remarks' },
  AI_NARRATIVE: { label: 'AI Narrative', icon: 'BrainCircuit', category: 'Remarks' },
  RECOMMENDATIONS: { label: 'Recommendations', icon: 'Lightbulb', category: 'Remarks' },
  STRENGTHS_WEAKNESSES: { label: 'Strengths & Weaknesses', icon: 'Target', category: 'Remarks' },
  SIGNATURE: { label: 'Signature', icon: 'PenTool', category: 'Official' },
  STAMP: { label: 'Stamp', icon: 'Stamp', category: 'Official' },
  SEAL: { label: 'Seal', icon: 'CircleDot', category: 'Official' },
  QR_CODE: { label: 'QR Code', icon: 'QrCode', category: 'Verification' },
  BADGE: { label: 'Badge', icon: 'Medal', category: 'Awards' },
  AWARD_TEXT: { label: 'Award Text', icon: 'ScrollText', category: 'Awards' },
  HEADER: { label: 'Header', icon: 'AlignStartVertical', category: 'Layout' },
  FOOTER: { label: 'Footer', icon: 'AlignEndVertical', category: 'Layout' },
  WATERMARK: { label: 'Watermark', icon: 'Droplets', category: 'Layout' },
  CUSTOM_TEXT: { label: 'Custom Text', icon: 'Pencil', category: 'Text' },
  TABLE: { label: 'Table', icon: 'Grid', category: 'Data' },
};

export const TEMPLATE_TYPES = [
  { value: 'REPORT_CARD', label: 'Report Card', icon: '📋' },
  { value: 'TRANSCRIPT', label: 'Academic Transcript', icon: '📜' },
  { value: 'ATTENDANCE_REPORT', label: 'Attendance Report', icon: '✅' },
  { value: 'STUDENT_PROFILE', label: 'Student Profile', icon: '👤' },
  { value: 'ANALYTICS_SUMMARY', label: 'Analytics Summary', icon: '📊' },
  { value: 'SCHOOL_PERFORMANCE', label: 'School Performance', icon: '🏫' },
  { value: 'CERTIFICATE', label: 'Certificate', icon: '🎓' },
  { value: 'TESTIMONIAL', label: 'Testimonial', icon: '✍️' },
  { value: 'RECOMMENDATION_LETTER', label: 'Recommendation', icon: '📝' },
  { value: 'MINISTRY_REPORT', label: 'Ministry Report', icon: '📑' },
  { value: 'ID_CARD', label: 'ID Card', icon: '🪪' },
  { value: 'FEE_STATEMENT', label: 'Fee Statement', icon: '💰' },
  { value: 'PROGRESS_REPORT', label: 'Progress Report', icon: '📈' },
];

export const CERTIFICATE_TYPES = [
  { value: 'ACADEMIC_EXCELLENCE', label: 'Academic Excellence', icon: '🎓' },
  { value: 'PARTICIPATION', label: 'Participation', icon: '🤝' },
  { value: 'GRADUATION', label: 'Graduation', icon: '🎉' },
  { value: 'ATTENDANCE', label: 'Attendance', icon: '✅' },
  { value: 'MERIT_AWARD', label: 'Merit Award', icon: '⭐' },
  { value: 'SPORTS_AWARD', label: 'Sports Award', icon: '🏅' },
  { value: 'LEADERSHIP_AWARD', label: 'Leadership Award', icon: '👑' },
];

export const PAGE_SIZES = ['A4', 'LETTER', 'LEGAL', 'A3'];
export const ORIENTATIONS = ['portrait', 'landscape'];
export const FONT_FAMILIES = ['Arial', 'Georgia', 'Times New Roman', 'Helvetica', 'Courier New', 'Verdana'];

export const PLACEHOLDER_DEFINITIONS = [
  { key: 'student_name', label: 'Student Full Name', category: 'Student' },
  { key: 'student_first_name', label: 'Student First Name', category: 'Student' },
  { key: 'student_last_name', label: 'Student Last Name', category: 'Student' },
  { key: 'student_photo', label: 'Student Photo URL', category: 'Student' },
  { key: 'student_admission', label: 'Admission Number', category: 'Student' },
  { key: 'class_name', label: 'Class Name', category: 'Academic' },
  { key: 'school_name', label: 'School Name', category: 'School' },
  { key: 'school_logo', label: 'School Logo URL', category: 'School' },
  { key: 'term', label: 'Term Name', category: 'Academic' },
  { key: 'term_name', label: 'Term Name', category: 'Academic' },
  { key: 'year', label: 'Academic Year', category: 'Academic' },
  { key: 'academic_year', label: 'Academic Year', category: 'Academic' },
  { key: 'attendance_percentage', label: 'Attendance %', category: 'Attendance' },
  { key: 'attendance_rate', label: 'Attendance Rate', category: 'Attendance' },
  { key: 'overall_grade', label: 'Overall Grade', category: 'Results' },
  { key: 'overall_score', label: 'Overall Score', category: 'Results' },
  { key: 'total_marks', label: 'Total Marks', category: 'Results' },
  { key: 'total_points', label: 'Total Points', category: 'Results' },
  { key: 'average_score', label: 'Average Score', category: 'Results' },
  { key: 'position', label: 'Class Position', category: 'Results' },
  { key: 'total_students', label: 'Total Students', category: 'Results' },
  { key: 'best_six', label: 'Best Six Points', category: 'Results' },
  { key: 'university_eligible', label: 'University Eligibility', category: 'Results' },
  { key: 'subject_count', label: 'Number of Subjects', category: 'Results' },
  { key: 'teacher_comment', label: 'Teacher Comment', category: 'Comments' },
  { key: 'head_comment', label: 'Head Teacher Comment', category: 'Comments' },
  { key: 'director_name', label: 'Director Name', category: 'Official' },
  { key: 'certificate_number', label: 'Certificate Number', category: 'Certificate' },
  { key: 'award_text', label: 'Award Text', category: 'Certificate' },
  { key: 'date', label: 'Current Date', category: 'System' },
  { key: 'ranking', label: 'Ranking', category: 'Analytics' },
  { key: 'percentile', label: 'Percentile', category: 'Analytics' },
  { key: 'z_score', label: 'Z-Score', category: 'Analytics' },
];

export const BORDER_STYLES = [
  { value: 'classic', label: 'Classic Double' },
  { value: 'modern', label: 'Modern Solid' },
  { value: 'elegant', label: 'Elegant Shadow' },
  { value: 'ornate', label: 'Ornate Frame' },
  { value: 'minimal', label: 'Minimal' },
  { value: 'gold', label: 'Gold Premium' },
];
