export const PERMISSIONS = {
  CLASS_VIEW: 'CLASS_VIEW',
  CLASS_MANAGE: 'CLASS_MANAGE',
  CLASS_STUDENT_VIEW: 'CLASS_STUDENT_VIEW',
  RESULTS_VIEW: 'RESULTS_VIEW',
  RESULTS_ENTER: 'RESULTS_ENTER',
  RESULTS_DELEGATED_ENTRY: 'RESULTS_DELEGATED_ENTRY',
  RESULTS_EDIT: 'RESULTS_EDIT',
  RESULTS_APPROVE: 'RESULTS_APPROVE',
  RESULTS_PUBLISH: 'RESULTS_PUBLISH',
  ATTENDANCE_VIEW: 'ATTENDANCE_VIEW',
  ATTENDANCE_MARK: 'ATTENDANCE_MARK',
  REPORT_VIEW: 'REPORT_VIEW',
  REPORT_GENERATE: 'REPORT_GENERATE',
  ANALYTICS_VIEW: 'ANALYTICS_VIEW',
  ASSIGNMENT_VIEW: 'ASSIGNMENT_VIEW',
  ASSIGNMENT_MANAGE: 'ASSIGNMENT_MANAGE',
  CALENDAR_VIEW: 'CALENDAR_VIEW',
  CALENDAR_CREATE: 'calendar:create',
  CALENDAR_UPDATE: 'calendar:update',
  CALENDAR_DELETE: 'calendar:delete',
  CALENDAR_MANAGE: 'CALENDAR_MANAGE',
  CALENDAR_PUBLISH: 'CALENDAR_PUBLISH',
  CALENDAR_EXPORT: 'CALENDAR_EXPORT',
  CALENDAR_IMPORT: 'calendar:import',
  CALENDAR_MANAGE_REMINDERS: 'calendar:manage_reminders',
  CALENDAR_MANAGE_SETTINGS: 'calendar:manage_settings',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const ROLE_DEFAULTS: Record<string, Permission[]> = {
  TEACHER: [
    PERMISSIONS.CLASS_VIEW,
    PERMISSIONS.CLASS_STUDENT_VIEW,
    PERMISSIONS.RESULTS_VIEW,
    PERMISSIONS.RESULTS_ENTER,
    PERMISSIONS.RESULTS_EDIT,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_GENERATE,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.CALENDAR_VIEW,
  ],
  'CLASS TEACHER': [
    PERMISSIONS.CLASS_VIEW,
    PERMISSIONS.CLASS_STUDENT_VIEW,
    PERMISSIONS.RESULTS_VIEW,
    PERMISSIONS.RESULTS_ENTER,
    PERMISSIONS.RESULTS_EDIT,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_GENERATE,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.CALENDAR_VIEW,
  ],
  HOD: [
    PERMISSIONS.CLASS_VIEW,
    PERMISSIONS.CLASS_STUDENT_VIEW,
    PERMISSIONS.RESULTS_VIEW,
    PERMISSIONS.RESULTS_ENTER,
    PERMISSIONS.RESULTS_EDIT,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.CALENDAR_VIEW,
  ],
  'SCHOOL STAFF': [PERMISSIONS.CALENDAR_VIEW],
  STAFF: [PERMISSIONS.CALENDAR_VIEW],
  HEADTEACHER: [PERMISSIONS.CALENDAR_VIEW, PERMISSIONS.CALENDAR_CREATE, PERMISSIONS.CALENDAR_UPDATE, PERMISSIONS.CALENDAR_DELETE, PERMISSIONS.CALENDAR_MANAGE, PERMISSIONS.CALENDAR_PUBLISH, PERMISSIONS.CALENDAR_EXPORT, PERMISSIONS.CALENDAR_IMPORT, PERMISSIONS.CALENDAR_MANAGE_REMINDERS, PERMISSIONS.CALENDAR_MANAGE_SETTINGS],
  DEPUTY: [PERMISSIONS.CALENDAR_VIEW, PERMISSIONS.CALENDAR_CREATE, PERMISSIONS.CALENDAR_UPDATE, PERMISSIONS.CALENDAR_DELETE, PERMISSIONS.CALENDAR_MANAGE, PERMISSIONS.CALENDAR_PUBLISH, PERMISSIONS.CALENDAR_EXPORT, PERMISSIONS.CALENDAR_IMPORT, PERMISSIONS.CALENDAR_MANAGE_REMINDERS, PERMISSIONS.CALENDAR_MANAGE_SETTINGS],
  'DEPUTY DIRECTOR': Object.values(PERMISSIONS),
  DIRECTOR: Object.values(PERMISSIONS),
  SUPERADMIN: Object.values(PERMISSIONS),
};

export function normalizeRole(role: string): string {
  const normalized = role.trim().toUpperCase();
  if (normalized === 'DEPUTY HEAD') return 'DEPUTY';
  if (normalized === 'SUPER_ADMIN') return 'SUPERADMIN';
  return normalized;
}

export function getDefaultPermissions(roles: string[] = []): Permission[] {
  const permissions = new Set<Permission>();
  for (const role of roles) {
    for (const permission of ROLE_DEFAULTS[normalizeRole(role)] || []) permissions.add(permission);
  }
  return Array.from(permissions);
}
