export const PERMISSIONS = {
  CLASS_VIEW: 'CLASS_VIEW',
  CLASS_MANAGE: 'CLASS_MANAGE',
  CLASS_STUDENT_VIEW: 'CLASS_STUDENT_VIEW',
  RESULTS_VIEW: 'RESULTS_VIEW',
  RESULTS_ENTER: 'RESULTS_ENTER',
  RESULTS_DELEGATED_ENTRY: 'RESULTS_DELEGATED_ENTRY',
  RESULTS_EDIT: 'RESULTS_EDIT',
  RESULTS_APPROVE: 'RESULTS_APPROVE',
  RESULTS_PUBLISH: 'RESULTS_PUBLISH',
  ATTENDANCE_VIEW: 'ATTENDANCE_VIEW',
  ATTENDANCE_MARK: 'ATTENDANCE_MARK',
  REPORT_VIEW: 'REPORT_VIEW',
  REPORT_GENERATE: 'REPORT_GENERATE',
  ANALYTICS_VIEW: 'ANALYTICS_VIEW',
  ASSIGNMENT_VIEW: 'ASSIGNMENT_VIEW',
  ASSIGNMENT_MANAGE: 'ASSIGNMENT_MANAGE',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const ROLE_DEFAULTS: Record<string, Permission[]> = {
  TEACHER: [
    PERMISSIONS.CLASS_VIEW,
    PERMISSIONS.CLASS_STUDENT_VIEW,
    PERMISSIONS.RESULTS_VIEW,
    PERMISSIONS.RESULTS_ENTER,
    PERMISSIONS.RESULTS_EDIT,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_GENERATE,
    PERMISSIONS.ANALYTICS_VIEW,
  ],
  'CLASS TEACHER': [
    PERMISSIONS.CLASS_VIEW,
    PERMISSIONS.CLASS_STUDENT_VIEW,
    PERMISSIONS.RESULTS_VIEW,
    PERMISSIONS.RESULTS_ENTER,
    PERMISSIONS.RESULTS_EDIT,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_GENERATE,
    PERMISSIONS.ANALYTICS_VIEW,
  ],
  HOD: [
    PERMISSIONS.CLASS_VIEW,
    PERMISSIONS.CLASS_STUDENT_VIEW,
    PERMISSIONS.RESULTS_VIEW,
    PERMISSIONS.RESULTS_ENTER,
    PERMISSIONS.RESULTS_EDIT,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
  ],
  'DEPUTY DIRECTOR': Object.values(PERMISSIONS),
  DIRECTOR: Object.values(PERMISSIONS),
  SUPERADMIN: Object.values(PERMISSIONS),
};

export function normalizeRole(role: string): string {
  const normalized = role.trim().toUpperCase();
  if (normalized === 'DEPUTY HEAD') return 'DEPUTY';
  if (normalized === 'SUPER_ADMIN') return 'SUPERADMIN';
  return normalized;
}

export function getDefaultPermissions(roles: string[] = []): Permission[] {
  const permissions = new Set<Permission>();
  for (const role of roles) {
    for (const permission of ROLE_DEFAULTS[normalizeRole(role)] || []) permissions.add(permission);
  }
  return Array.from(permissions);
}
