import React, { useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, RefreshControl, StyleSheet, Text, View } from 'react-native';
import { apiService } from '../../services/api';

export const BusinessCalendarScreen: React.FC = () => {
  const [items, setItems] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const load = async () => { try { const calendars = await apiService.getBusinessCalendars(true); const calendar = calendars?.[0]; setItems(calendar ? await apiService.getBusinessCalendarActivities(calendar.id) : []); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  return <View style={styles.page}><Text style={styles.eyebrow}>INSTITUTIONAL CALENDAR</Text><Text style={styles.title}>School Business Calendar</Text><Text style={styles.subtitle}>Published activities, deadlines, meetings and assessments.</Text>{loading ? <ActivityIndicator color="#0e7490" style={styles.loader} /> : <FlatList data={items} keyExtractor={(item) => item.id} refreshControl={<RefreshControl refreshing={loading} onRefresh={() => { setLoading(true); load(); }} />} ListEmptyComponent={<Text style={styles.empty}>No published activities are available.</Text>} renderItem={({ item }) => <View style={styles.card}><View style={styles.date}><Text style={styles.day}>{new Date(item.startDate).getDate()}</Text><Text style={styles.month}>{new Date(item.startDate).toLocaleString('en', { month: 'short' }).toUpperCase()}</Text></View><View style={styles.content}><Text style={styles.activity}>{item.title}</Text><Text style={styles.meta}>{item.startTime || 'All day'}  ·  {item.venue || 'Venue TBC'}</Text><Text style={styles.status}>{item.status}</Text></View></View>} />}</View>;
};

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: '#f4f7f9', padding: 20 }, eyebrow: { color: '#0e7490', fontSize: 11, fontWeight: '800', letterSpacing: 1.5 }, title: { color: '#123047', fontSize: 28, fontWeight: '800', marginTop: 6 }, subtitle: { color: '#64748b', fontSize: 14, marginTop: 6, marginBottom: 20 }, loader: { marginTop: 40 }, empty: { color: '#64748b', textAlign: 'center', marginTop: 50 }, card: { backgroundColor: '#fff', borderRadius: 14, padding: 15, marginBottom: 11, flexDirection: 'row', borderWidth: 1, borderColor: '#e2e8f0' }, date: { width: 52, height: 52, borderRadius: 10, backgroundColor: '#e0f2fe', justifyContent: 'center', alignItems: 'center' }, day: { color: '#0e7490', fontSize: 22, fontWeight: '800' }, month: { color: '#0e7490', fontSize: 9, fontWeight: '800' }, content: { flex: 1, marginLeft: 14 }, activity: { color: '#0f172a', fontSize: 16, fontWeight: '700' }, meta: { color: '#64748b', fontSize: 12, marginTop: 5 }, status: { color: '#0369a1', fontSize: 10, fontWeight: '800', marginTop: 7, textTransform: 'uppercase' } });
