import { IsOptional, IsString, IsDateString, IsInt, Min, IsObject } from 'class-validator';

export class UpdateStaffHrProfileDto {
  @IsOptional() @IsString() employeeNumber?: string;
  @IsOptional() @IsString() province?: string;
  @IsOptional() @IsString() district?: string;
  @IsOptional() @IsString() station?: string;
  @IsOptional() @IsString() teacherName?: string;
  @IsOptional() @IsString() gender?: string;
  @IsOptional() @IsDateString() dateOfBirth?: string;
  @IsOptional() @IsString() maritalStatus?: string;
  @IsOptional() @IsString() nrcNumber?: string;
  @IsOptional() @IsString() tsNumber?: string;
  @IsOptional() @IsString() aesNumber?: string;
  @IsOptional() @IsString() substantivePosition?: string;
  @IsOptional() @IsString() substantiveScale?: string;
  @IsOptional() @IsString() actingPosition?: string;
  @IsOptional() @IsString() administration?: string;
  @IsOptional() @IsString() actingType?: string;
  @IsOptional() @IsDateString() dateOfFirstAppointment?: string;
  @IsOptional() @IsDateString() dateOfPresentAppointment?: string;
  @IsOptional() @IsDateString() dateOfActingAppointment?: string;
  @IsOptional() @IsString() confirmed?: string;
  @IsOptional() @IsDateString() expectedConfirmationDate?: string;
  @IsOptional() @IsString() allowancesEntitled?: string;
  @IsOptional() @IsString() employmentStatus?: string;
  @IsOptional() @IsString() employmentType?: string;
  @IsOptional() @IsDateString() contractEffectiveDate?: string;
  @IsOptional() @IsString() contractNormalised?: string;
  @IsOptional() @IsDateString() contractEnd?: string;
  @IsOptional() @IsDateString() retirementDate?: string;
  @IsOptional() @IsString() payrollPoint?: string;
  @IsOptional() @IsString() academicQualification?: string;
  @IsOptional() @IsString() professionalQualification?: string;
  @IsOptional() @IsInt() @Min(1900) yearOfQualification?: number;
  @IsOptional() @IsString() specialization?: string;
  @IsOptional() @IsString() nationality?: string;
  @IsOptional() @IsString() emailAddress?: string;
  @IsOptional() @IsString() phoneNumber?: string;
  @IsOptional() @IsString() currentPosition?: string;
  @IsOptional() @IsString() gradeLevel?: string;
  @IsOptional() @IsInt() @Min(1) step?: number;
  @IsOptional() @IsString() taxId?: string;
  @IsOptional() @IsString() pensionNumber?: string;
  @IsOptional() @IsString() bankName?: string;
  @IsOptional() @IsString() bankBranch?: string;
  @IsOptional() @IsString() bankAccount?: string;
  @IsOptional() @IsString() socialSecurityNumber?: string;
  @IsOptional() @IsString() nextOfKin?: string;
  @IsOptional() @IsString() nextOfKinContact?: string;
  @IsOptional() @IsString() nextOfKinRelationship?: string;
  @IsOptional() @IsObject() dynamicFields?: Record<string, any>;
}
