export const colors = {
  primary: '#1E3A8A',
  primaryLight: '#3B82F6',
  primaryDark: '#1E2A5A',
  secondary: '#14B8A6',
  secondaryLight: '#5EEAD4',
  accent: '#F59E0B',
  accentLight: '#FCD34D',
  accentDark: '#D97706',
  background: '#F3F4F6',
  white: '#FFFFFF',
  text: '#1F2937',
  textSecondary: '#374151',
  textLight: '#6B7280',
  textMuted: '#9CA3AF',
  border: '#E5E7EB',
  borderLight: '#F3F4F6',
  success: '#10B981',
  successLight: '#D1FAE5',
  error: '#EF4444',
  errorLight: '#FEE2E2',
  warning: '#F59E0B',
  warningLight: '#FEF3C7',
  info: '#3B82F6',
  infoLight: '#DBEAFE',
  teal: '#0D9488',
  tealLight: '#CCFBF1',
  orange: '#EA580C',
  orangeLight: '#FFEDD5',
  purple: '#8B5CF6',
  purpleLight: '#EDE9FE',
  pink: '#EC4899',
  pinkLight: '#FCE7F3',
  gradient: {
    blue: ['#1E3A8A', '#3B82F6'] as const,
    blueLight: ['#3B82F6', '#60A5FA'] as const,
    teal: ['#0D9488', '#14B8A6'] as const,
    orange: ['#EA580C', '#F97316'] as const,
    purple: ['#7C3AED', '#A78BFA'] as const,
    accent: ['#D97706', '#F59E0B'] as const,
    cardBlue: ['#EFF6FF', '#DBEAFE'] as const,
    cardTeal: ['#CCFBF1', '#F0FDFA'] as const,
    cardOrange: ['#FFEDD5', '#FFF7ED'] as const,
    cardPurple: ['#EDE9FE', '#F5F3FF'] as const,
  },
};

export const spacing = {
  xs: 4,
  sm: 8,
  md: 14,
  lg: 20,
  xl: 28,
  xxl: 40,
};

export const borderRadius = {
  sm: 6,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 28,
  full: 9999,
};

export const typography = {
  h1: {
    fontSize: 28,
    fontWeight: '700' as const,
    color: colors.text,
    letterSpacing: -0.5,
  },
  h2: {
    fontSize: 24,
    fontWeight: '700' as const,
    color: colors.text,
    letterSpacing: -0.3,
  },
  h3: {
    fontSize: 20,
    fontWeight: '600' as const,
    color: colors.text,
  },
  h4: {
    fontSize: 17,
    fontWeight: '600' as const,
    color: colors.text,
  },
  body: {
    fontSize: 15,
    fontWeight: '400' as const,
    color: colors.text,
    lineHeight: 22,
  },
  bodySmall: {
    fontSize: 13,
    fontWeight: '400' as const,
    color: colors.textLight,
    lineHeight: 18,
  },
  caption: {
    fontSize: 11,
    fontWeight: '500' as const,
    color: colors.textLight,
    letterSpacing: 0.3,
    textTransform: 'uppercase' as const,
  },
  captionSmall: {
    fontSize: 10,
    fontWeight: '600' as const,
    color: colors.textMuted,
    letterSpacing: 0.4,
    textTransform: 'uppercase' as const,
  },
  metric: {
    fontSize: 32,
    fontWeight: '700' as const,
    color: colors.text,
    letterSpacing: -1,
  },
  metricSmall: {
    fontSize: 24,
    fontWeight: '700' as const,
    color: colors.text,
    letterSpacing: -0.5,
  },
};

export const shadows = {
  sm: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
    elevation: 1,
  },
  md: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  lg: {
    shadowColor: '#1E3A8A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 5,
  },
  card: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 3,
  },
  header: {
    shadowColor: '#1E3A8A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
};
